[2025-03-12T08:16:51.273+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T08:16:51.888+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_category_analysis.category_stocks_analysis manual__2025-03-12T08:08:41.718880+00:00 [queued]>
[2025-03-12T08:16:51.928+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_category_analysis.category_stocks_analysis manual__2025-03-12T08:08:41.718880+00:00 [queued]>
[2025-03-12T08:16:51.929+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-12T08:16:52.013+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): category_stocks_analysis> on 2025-03-12 08:08:41.718880+00:00
[2025-03-12T08:16:52.035+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T08:16:52.044+0000] {standard_task_runner.py:72} INFO - Started process 95 to run task
[2025-03-12T08:16:52.045+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_category_analysis', 'category_stocks_analysis', 'manual__2025-03-12T08:08:41.718880+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/data/scheduled.py', '--cfg-path', '/tmp/tmpv5z8weez']
[2025-03-12T08:16:52.060+0000] {standard_task_runner.py:105} INFO - Job 342: Subtask category_stocks_analysis
[2025-03-12T08:16:52.246+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_category_analysis.category_stocks_analysis manual__2025-03-12T08:08:41.718880+00:00 [running]> on host fc342882eb4f
[2025-03-12T08:16:52.628+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_category_analysis' AIRFLOW_CTX_TASK_ID='category_stocks_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T08:08:41.718880+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T08:08:41.718880+00:00'
[2025-03-12T08:16:52.631+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T08:16:52.633+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T08:16:52.643+0000] {logging_mixin.py:190} INFO - Current task name:category_stocks_analysis state:running start_date:2025-03-12 08:16:51.890158+00:00
[2025-03-12T08:16:52.645+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis and current dag run status:running
[2025-03-12T08:16:52.649+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T08:16:52.680+0000] {logging_mixin.py:190} INFO - Category stocks analysis failed: [Errno 2] No such file or directory: '/opt/***/dags/data/data/categories.csv'
[2025-03-12T08:16:52.688+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/scheduled.py", line 61, in analyze_category_stocks
    categories_df = pd.read_csv(os.path.join(os.path.dirname(__file__), 'data', 'categories.csv'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/data/categories.csv'
[2025-03-12T08:16:52.818+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-12T08:16:52.820+0000] {logging_mixin.py:190} INFO - Task start:2025-03-12 08:16:51.890158+00:00 end:2025-03-12 08:16:52.817740+00:00 duration:0.927582
[2025-03-12T08:16:52.832+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): category_stocks_analysis> dag:<DAG: weekly_category_analysis> dagrun:<DagRun weekly_category_analysis @ 2025-03-12 08:08:41.718880+00:00: manual__2025-03-12T08:08:41.718880+00:00, state:running, queued_at: 2025-03-12 08:08:41.799977+00:00. externally triggered: True>
[2025-03-12T08:16:52.851+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/dags/data/data/categories.csv'
[2025-03-12T08:16:52.858+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=weekly_category_analysis, task_id=category_stocks_analysis, run_id=manual__2025-03-12T08:08:41.718880+00:00, execution_date=20250312T080841, start_date=20250312T081651, end_date=20250312T081652
[2025-03-12T08:16:53.024+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T08:16:53.032+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 342 for task category_stocks_analysis ([Errno 2] No such file or directory: '/opt/airflow/dags/data/data/categories.csv'; 95)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data/scheduled.py", line 61, in analyze_category_stocks
    categories_df = pd.read_csv(os.path.join(os.path.dirname(__file__), 'data', 'categories.csv'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/data/categories.csv'
[2025-03-12T08:16:53.128+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-12T08:16:53.158+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
