[2025-03-12T15:05:35.554+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T15:05:35.649+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_all_tables.orders scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:35.689+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_all_tables.orders scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:35.690+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T15:05:35.777+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): orders> on 2025-03-05 13:00:00+00:00
[2025-03-12T15:05:35.801+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1306) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T15:05:35.808+0000] {standard_task_runner.py:72} INFO - Started process 1318 to run task
[2025-03-12T15:05:35.822+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'validate_all_tables', 'orders', 'scheduled__2025-03-05T13:00:00+00:00', '--job-id', '484', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmpxf24skz8']
[2025-03-12T15:05:35.843+0000] {standard_task_runner.py:105} INFO - Job 484: Subtask orders
[2025-03-12T15:05:36.107+0000] {task_command.py:467} INFO - Running <TaskInstance: validate_all_tables.orders scheduled__2025-03-05T13:00:00+00:00 [running]> on host b404e9833d11
[2025-03-12T15:05:36.468+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_all_tables' AIRFLOW_CTX_TASK_ID='orders' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-05T13:00:00+00:00'
[2025-03-12T15:05:36.483+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T15:05:36.489+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T15:05:36.514+0000] {logging_mixin.py:190} INFO - Current task name:orders state:running start_date:2025-03-12 15:05:35.652027+00:00
[2025-03-12T15:05:36.523+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables and current dag run status:running
[2025-03-12T15:05:36.524+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T15:05:38.379+0000] {httpchecksum.py:481} INFO - Skipping checksum validation. Response did not contain one of the following algorithms: ['crc32', 'sha1', 'sha256'].
[2025-03-12T15:05:39.343+0000] {logging_mixin.py:190} INFO - Validation successful. Found 1615 order records.
[2025-03-12T15:05:39.345+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T15:05:39.388+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T15:05:39.391+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=validate_all_tables, task_id=orders, run_id=scheduled__2025-03-05T13:00:00+00:00, execution_date=20250305T130000, start_date=20250312T150535, end_date=20250312T150539
[2025-03-12T15:05:39.571+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-12T15:05:39.578+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-12T15:05:39.593+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables queued_at:2025-03-12 15:04:59.240294+00:00
[2025-03-12T15:05:39.612+0000] {logging_mixin.py:190} INFO - Task hostname:b404e9833d11 operator:PythonOperator
[2025-03-12T15:05:39.730+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T15:05:39.866+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T15:05:39.918+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
